"""Hand-written page content for every actor, in English and German.

Kept separate from the Apify READMEs on purpose: copied text would be duplicate
content for Google. Prices are NOT written here — build.py reads them live from
the Apify Store every day.
"""

GROUPS = {
    "ai": {"en": "For AI and RAG", "de": "Für KI und RAG"},
    "sales": {"en": "For sales and lead generation", "de": "Für Vertrieb und Leadgenerierung"},
    "research": {"en": "For market and competitor research", "de": "Für Markt- und Wettbewerbsanalyse"},
    "public": {"en": "Public and regulatory data", "de": "Öffentliche und regulatorische Daten"},
    "free": {"en": "Free tools", "de": "Kostenlose Werkzeuge"},
}

ACTORS = {
    "research-agent": {
        "icon": "research-agent-256.png", "group": "ai",
        "unit": {"en": "questions", "de": "Fragen"},
        "example": {"query": "What obligations do providers of high-risk AI systems have under the EU AI Act?",
                    "sources": ["web", "law"], "preferEvidence": "official_first"},
        "en": {
            "title": "Research Agent – Cited Web Search API for RAG and AI Agents",
            "h1": "Cited answers your AI can trust — with an evidence check",
            "desc": "Ask a question, get cited passages from Google, official EU and German law, research papers and Wikipedia — with evidence levels, a fact cross-check and freshness warnings.",
            "intro": "One call searches the web, news, official legal texts, open-access research, Wikipedia, Stack Overflow, Hacker News and GitHub, reads the pages in full and keeps only the passages that answer the question. Each source gets an evidence level, figures are compared across independent sites, and outdated or amended information is flagged — so your model knows how far to trust its context.",
            "features": ["Evidence level for every source — official, academic, preprint, institution, reference, news, documentation, community or commercial",
                         "Figures cross-checked across independent sites: consistent, single source or conflicting, with the sentences side by side",
                         "Freshness check: age of the sources and wording such as “amended by”, “repealed” or “postponed”",
                         "Official legal texts: EU law in its current consolidated version (24 languages) and German federal law — name a provision and it is cited first",
                         "Open-access papers read in full, not just abstracts",
                         "Ready-to-paste context with numbered citations, or one row per passage with stable IDs for vector databases"],
            "uses": ["Grounding for AI agents and chatbots (MCP, LangChain, n8n, API)", "Compliance assistants that must quote the law",
                     "Checking figures before they reach a report", "Feeding a vector database with cited, deduplicated chunks"],
            "price_note": "Billed by Apify per answered question; each further Google search (news, legal-text search, second round) is billed separately. Questions without results, answers without Google and the example question are free.",
            "faq": [("Is a language model involved?", "No. Search, ranking and all checks are rule-based and reproducible, and nothing is sent to an AI provider."),
                    ("What is not charged?", "Questions without relevant results, answers given without Google (status partial), skipped or failed questions and the example question."),
                    ("How is the quality checked?", "Every Sunday an automated watchdog re-runs all published examples on the live actor and checks the results — for legal questions, for example, that the named provision is cited from the official text first.")],
        },
        "de": {
            "title": "Research Agent – belegte Websuche für RAG und KI-Agenten",
            "h1": "Belegte Antworten, denen Ihre KI vertrauen kann — mit Evidenz-Check",
            "desc": "Frage stellen, belegte Textstellen aus Google, amtlichem EU- und Bundesrecht, Fachartikeln und Wikipedia erhalten — mit Evidenzstufe, Faktenabgleich und Aktualitätswarnung.",
            "intro": "Ein Aufruf durchsucht Web, Nachrichten, amtliche Rechtstexte, frei zugängliche Forschung, Wikipedia, Stack Overflow, Hacker News und GitHub, liest die Seiten vollständig und behält nur die Textstellen, die die Frage beantworten. Jede Quelle bekommt eine Evidenzstufe, Zahlen werden über unabhängige Seiten abgeglichen, veraltete oder geänderte Angaben werden markiert — so weiß Ihr Modell, wie weit es dem Kontext trauen kann.",
            "features": ["Evidenzstufe je Quelle — amtlich, wissenschaftlich, Preprint, Institution, Nachschlagewerk, Nachrichten, Dokumentation, Community oder kommerziell",
                         "Zahlen über unabhängige Seiten abgeglichen: übereinstimmend, nur eine Quelle oder widersprüchlich — mit den Sätzen nebeneinander",
                         "Aktualitäts-Check: Alter der Quellen und Formulierungen wie „geändert durch“, „aufgehoben“ oder „verschoben“",
                         "Amtliche Rechtstexte: EU-Recht in der aktuellen konsolidierten Fassung (24 Sprachen) und Bundesrecht — genannte Vorschriften stehen an erster Stelle",
                         "Frei zugängliche Fachartikel vollständig gelesen, nicht nur die Zusammenfassung",
                         "Fertiger Kontext mit nummerierten Quellen oder eine Zeile je Textstelle mit stabiler ID für Vektordatenbanken"],
            "uses": ["Fundierte Antworten für KI-Agenten und Chatbots (MCP, LangChain, n8n, API)", "Compliance-Assistenten, die das Gesetz zitieren müssen",
                     "Zahlen prüfen, bevor sie in einen Bericht gehen", "Vektordatenbanken mit belegten, bereinigten Textabschnitten füllen"],
            "price_note": "Abrechnung über Apify je beantworteter Frage; jede weitere Google-Suche (Nachrichten, Rechtstext-Suche, zweite Runde) wird einzeln berechnet. Fragen ohne Ergebnis, Antworten ohne Google und die Beispielfrage sind kostenlos.",
            "faq": [("Wird ein Sprachmodell verwendet?", "Nein. Suche, Rangfolge und alle Prüfungen sind regelbasiert und nachvollziehbar, und nichts geht an einen KI-Anbieter."),
                    ("Was wird nicht berechnet?", "Fragen ohne passende Treffer, Antworten ohne Google (Status partial), übersprungene oder fehlgeschlagene Fragen und die Beispielfrage."),
                    ("Wie wird die Qualität geprüft?", "Jeden Sonntag führt ein automatischer Wachposten alle veröffentlichten Beispiele mit dem Live-Actor neu aus und prüft die Ergebnisse — bei Rechtsfragen etwa, ob die genannte Vorschrift aus dem amtlichen Text zuerst zitiert wird.")],
        },
    },
    "pdf-to-markdown-converter": {
        "icon": "doc-markdown-256.png", "group": "ai",
        "unit": {"en": "pages", "de": "Seiten"},
        "example": {"crawler_dataset": "<run ID of a Website Content Crawler run>", "output": "chunks", "chunk_size": 1500},
        "en": {
            "title": "PDF & DOCX to Markdown Converter for AI and RAG",
            "h1": "Convert PDF, Word, Excel and PowerPoint to Markdown for AI",
            "desc": "Turn PDF, DOCX, XLSX and PPTX files into clean Markdown with tables as JSON and OCR for scans — per document, page or RAG chunk. No LLM involved.",
            "intro": "Language models read Markdown far better than PDFs. This converter turns documents into clean Markdown and plain text, keeps tables as real tables and as JSON rows, and reads scanned pages with OCR. It also fills in the files that Apify's Website Content Crawler downloads but leaves empty.",
            "features": ["PDF with text layer: reading order, headings, tables", "Scanned pages read with OCR in eight languages", "Word, Excel, PowerPoint, HTML, CSV and more", "Output per document, per page or as RAG chunks with page numbers", "Your files never go to an outside AI provider"],
            "uses": ["Feed company documents into a vector database", "Extract tables from reports and statistics", "Make scanned archives searchable", "Complete a website crawl with its PDFs and Office files"],
            "faq": [("Does it work with scanned PDFs?", "Yes. Pages without a text layer are detected and read with OCR; blank pages and chapter dividers are skipped so you are not charged for them."),
                    ("Which file types are supported?", "PDF, DOCX, XLSX, XLS, PPTX, HTML, CSV, JSON, XML and plain text. Old binary .doc and .ppt files are not supported."),
                    ("Is an LLM used?", "No. Conversion runs inside your own Apify run with open-source tools, so documents stay private and costs stay low.")],
        },
        "de": {
            "title": "PDF, Word und Excel in Markdown umwandeln – für KI & RAG",
            "h1": "PDF, Word, Excel und PowerPoint in Markdown umwandeln",
            "desc": "PDF-, DOCX-, XLSX- und PPTX-Dateien in sauberes Markdown umwandeln: Tabellen als JSON, Texterkennung für Scans, Ausgabe je Dokument, Seite oder RAG-Abschnitt.",
            "intro": "KI-Modelle verstehen Markdown deutlich besser als PDF. Dieser Konverter macht aus Dokumenten sauberes Markdown und reinen Text, erhält Tabellen als echte Tabellen und als JSON-Zeilen und liest eingescannte Seiten per Texterkennung (OCR). Er füllt außerdem die Dateien, die Apifys Website Content Crawler herunterlädt, aber leer lässt.",
            "features": ["PDF mit Textebene: Lesereihenfolge, Überschriften, Tabellen", "Eingescannte Seiten per OCR, auch auf Deutsch", "Word, Excel, PowerPoint, HTML, CSV und mehr", "Ausgabe je Dokument, je Seite oder als RAG-Abschnitte mit Seitenzahlen", "Ihre Dateien gehen an keinen externen KI-Dienst"],
            "uses": ["Firmendokumente in eine Vektordatenbank laden", "Tabellen aus Berichten und Statistiken auslesen", "Gescannte Archive durchsuchbar machen", "Einen Website-Crawl um seine PDFs und Office-Dateien ergänzen"],
            "faq": [("Funktioniert das mit eingescannten PDFs?", "Ja. Seiten ohne Textebene werden erkannt und per OCR gelesen; leere Seiten und Kapiteltrenner werden übersprungen und nicht berechnet."),
                    ("Welche Dateitypen werden unterstützt?", "PDF, DOCX, XLSX, XLS, PPTX, HTML, CSV, JSON, XML und Text. Alte .doc- und .ppt-Dateien werden nicht unterstützt."),
                    ("Wird eine KI verwendet?", "Nein. Die Umwandlung läuft mit Open-Source-Werkzeugen im eigenen Apify-Lauf — die Dokumente bleiben vertraulich, die Kosten niedrig.")],
        },
    },
    "google-ads-transparency-scraper": {
        "icon": "ads-transparency-256.png", "group": "sales",
        "unit": {"en": "ads", "de": "Anzeigen"},
        "example": {"mode": "companies", "domains": ["check24.de", "otto.de", "frischpack.de"], "region_breakdown": ["DE", "AT", "CH"]},
        "en": {
            "title": "Google Ads Transparency + Bing Ads Library Scraper",
            "h1": "Check which companies advertise on Google and Bing — in bulk",
            "desc": "Check company lists against Google Ads Transparency and the Microsoft Ad Library: who advertises, how many ads, which accounts, active in the last 30 days.",
            "intro": "Google and Microsoft both publish the ads they serve. This actor checks 10 or 10,000 company domains or names against both libraries in one run and returns one row per company — advertising on Google, on Bing, roughly how many ads, which advertiser accounts run them and whether they ran recently. Every Microsoft account is checked against the landing pages of its own ads, so a name lookalike never counts.",
            "features": ["Google and Bing in one row per company", "Every Bing account proven by its own ads' landing pages", "Own advertiser vs. agencies and resellers", "Ads per country, e.g. Germany, Austria, Switzerland", "Export ads — Bing with text, landing page, reach and targeting", "Monitoring mode: only new ads, on both platforms"],
            "uses": ["Qualify leads for an ads agency or SaaS", "Find companies on Google Ads but not on Bing", "Watch competitors launch new campaigns", "See who else runs ads linking to your domain"],
            "faq": [("Where does the data come from?", "From Google's Ads Transparency Center and Microsoft's Ad Library, which both companies publish under the EU Digital Services Act. No login is involved."),
                    ("Can I see ad spend?", "Neither publishes spend. Google gives the number of ads, Microsoft also a reach range per ad — together with how recently ads ran, the best public signal."),
                    ("Which countries does Bing cover?", "Microsoft publishes ads shown in the EU and EEA. Google covers every country.")],
        },
        "de": {
            "title": "Google- und Bing-Werbung prüfen: Wer wirbt? Firmenlisten",
            "h1": "Prüfen, welche Firmen bei Google und Bing werben — für ganze Listen",
            "desc": "Firmenlisten gegen Google Ads Transparency und die Microsoft Ad Library prüfen: wer wirbt, wie viele Anzeigen, welche Konten, aktiv in den letzten 30 Tagen.",
            "intro": "Google und Microsoft veröffentlichen die Anzeigen, die sie ausspielen. Dieser Actor prüft 10 oder 10.000 Domains oder Firmennamen in einem Lauf gegen beide Bibliotheken und liefert je Firma eine Zeile: wirbt sie bei Google, bei Bing, mit wie vielen Anzeigen ungefähr, über welche Konten und ob die Anzeigen zuletzt liefen. Jedes Microsoft-Konto wird an den Zielseiten seiner eigenen Anzeigen geprüft — Namensvettern zählen nie mit.",
            "features": ["Google und Bing in einer Zeile je Firma", "Jedes Bing-Konto über die Zielseiten seiner Anzeigen belegt", "Eigene Werbung vs. Agenturen und Händler", "Anzeigen je Land, z. B. Deutschland, Österreich, Schweiz", "Anzeigen exportieren — bei Bing mit Text, Zielseite, Reichweite und Targeting", "Überwachung: nur neue Anzeigen, auf beiden Plattformen"],
            "uses": ["Leads für Agenturen und SaaS-Anbieter qualifizieren", "Firmen finden, die bei Google werben, aber nicht bei Bing", "Neue Kampagnen von Wettbewerbern beobachten", "Sehen, wer sonst mit Ihrer Domain wirbt"],
            "faq": [("Woher stammen die Daten?", "Aus Googles Ads Transparency Center und Microsofts Ad Library, die beide nach dem Digital Services Act veröffentlicht werden. Ohne Login."),
                    ("Sieht man die Werbeausgaben?", "Keiner von beiden veröffentlicht Ausgaben. Google nennt die Anzahl der Anzeigen, Microsoft zusätzlich eine Reichweitenspanne je Anzeige — zusammen mit der Aktualität das beste öffentliche Signal."),
                    ("Welche Länder deckt Bing ab?", "Microsoft veröffentlicht Anzeigen, die in der EU und im EWR liefen. Google deckt alle Länder ab.")],
        },
    },
    "imprint-impressum-website-contact-scraper": {
        "icon": "impressum-256.png", "group": "sales",
        "unit": {"en": "websites", "de": "Websites"},
        "example": {"websites": ["liebherr.com", "frischpack.de"], "validate_vat": True},
        "en": {
            "title": "Imprint & Impressum Scraper – DACH Company Data",
            "h1": "Company data from the Impressum of any German, Austrian or Swiss website",
            "desc": "Turn domains into verified company records: legal name, address, register number, VIES-checked VAT ID, e-mail, phone and socials from the Impressum.",
            "intro": "Every commercial website in Germany, Austria and Switzerland must publish an imprint (Impressum) by law. This actor reads it and returns a clean company record — and checks every VAT ID live against the EU's VIES register. No domain list? Search by trade and city instead.",
            "features": ["Legal name, legal form and address", "Commercial register (HRB, Firmenbuch, Swiss UID)", "VAT ID verified live against EU VIES", "E-mails, phones and social profiles", "Find businesses by trade and city via OpenStreetMap"],
            "uses": ["Enrich and clean CRM records", "Verify supplier and customer master data", "Check VAT IDs in bulk", "Build company lists for a trade and region"],
            "faq": [("What is an Impressum?", "The legal notice German, Austrian and Swiss websites must publish: who runs the site, where it is registered and how to reach it."),
                    ("Are person names included?", "Off by default. Managing directors are personal data under GDPR and must be switched on deliberately."),
                    ("Can I use the e-mails for cold outreach?", "In Germany, promotional e-mail to companies needs prior consent (§ 7 UWG).")],
        },
        "de": {
            "title": "Impressum-Daten extrahieren – Firmendaten aus Websites",
            "h1": "Impressum-Daten aus Websites extrahieren: Firmendaten für DACH",
            "desc": "Aus Domains geprüfte Firmendatensätze: Firmenname, Anschrift, Handelsregister, per VIES geprüfte USt-IdNr., E-Mail, Telefon und Social-Media-Profile.",
            "intro": "Jede geschäftliche Website in Deutschland, Österreich und der Schweiz muss ein Impressum haben. Dieser Actor liest es aus und liefert einen sauberen Firmendatensatz — und prüft jede USt-IdNr. live gegen das EU-Register VIES. Keine Domainliste? Dann einfach nach Branche und Ort suchen.",
            "features": ["Firmenname, Rechtsform und Anschrift", "Handelsregister (HRB, Firmenbuch, Schweizer UID)", "USt-IdNr. live gegen EU-VIES geprüft", "E-Mail-Adressen, Telefonnummern, Social-Media-Profile", "Firmen nach Branche und Ort finden (OpenStreetMap)"],
            "uses": ["CRM-Daten anreichern und bereinigen", "Lieferanten- und Kundenstammdaten prüfen", "USt-IdNr. in großer Zahl verifizieren", "Firmenlisten für Branche und Region aufbauen"],
            "faq": [("Was steht im Impressum?", "Wer die Website betreibt, wo die Firma eingetragen ist und wie sie erreichbar ist — Pflicht nach § 5 DDG."),
                    ("Werden Personennamen ausgegeben?", "Standardmäßig nicht. Geschäftsführer sind personenbezogene Daten nach DSGVO und müssen bewusst eingeschaltet werden."),
                    ("Darf ich die E-Mails für Werbung nutzen?", "Werbe-E-Mails an Firmen brauchen in Deutschland eine vorherige Einwilligung (§ 7 UWG).")],
        },
    },
    "free-website-contact-imprint-scraper": {
        "icon": "impressum-256.png", "group": "free",
        "unit": {"en": "websites", "de": "Websites"},
        "example": {"websites": ["liebherr.com", "frischpack.de", "tuwien.at"]},
        "en": {
            "title": "Free Website Contact & Imprint Scraper (10 per run)",
            "h1": "Free imprint and contact scraper — 10 websites per run",
            "desc": "Free: company name, address, register number, VIES-checked VAT ID, e-mails and phones from the imprint of up to 10 websites per run.",
            "intro": "The free edition of the Imprint & Impressum Scraper: the same fields, the same VAT check, limited to 10 websites per run. Ideal for trying it out or for small lists.",
            "features": ["Up to 10 websites per run, free", "Exactly the same fields as the paid edition", "VAT IDs checked against EU VIES", "Search by trade and city via OpenStreetMap"],
            "uses": ["Test the data before a bigger run", "Look up a handful of suppliers", "Check a VAT ID quickly"],
            "faq": [("Is it really free?", "There is no actor fee. Runs use a few cents of platform time, which Apify's free monthly credit covers."),
                    ("What if I need more than 10?", "The paid Imprint & Impressum Scraper has no cap.")],
        },
        "de": {
            "title": "Kostenloser Impressum-Scraper – 10 Websites pro Lauf",
            "h1": "Impressum und Kontaktdaten kostenlos auslesen",
            "desc": "Kostenlos: Firmenname, Anschrift, Handelsregister, geprüfte USt-IdNr., E-Mail und Telefon aus dem Impressum von bis zu 10 Websites pro Lauf.",
            "intro": "Die kostenlose Ausgabe des Impressum-Scrapers: dieselben Felder, dieselbe USt-Prüfung, begrenzt auf 10 Websites pro Lauf. Ideal zum Ausprobieren und für kleine Listen.",
            "features": ["Bis zu 10 Websites pro Lauf, kostenlos", "Exakt dieselben Felder wie die Vollversion", "USt-IdNr. gegen EU-VIES geprüft", "Suche nach Branche und Ort über OpenStreetMap"],
            "uses": ["Daten vor einem großen Lauf testen", "Einige Lieferanten nachschlagen", "Eine USt-IdNr. schnell prüfen"],
            "faq": [("Ist das wirklich kostenlos?", "Es gibt keine Actor-Gebühr. Die wenigen Cent Plattformzeit deckt Apifys monatliches Gratisguthaben."),
                    ("Und wenn ich mehr als 10 brauche?", "Der kostenpflichtige Impressum-Scraper hat keine Obergrenze.")],
        },
    },
    "messe-muenchen-exhibitor-list-scraper": {
        "icon": "messe-muenchen-256.png", "group": "sales",
        "unit": {"en": "exhibitors", "de": "Aussteller"},
        "example": {"start_url": "https://exhibitors.bauma.de/", "result_limit": 500},
        "en": {
            "title": "Messe München Exhibitor List Scraper – bauma, IFAT, BAU",
            "h1": "Export exhibitor lists of Messe München trade fairs",
            "desc": "Export bauma, IFAT, BAU, automatica and ceramitec exhibitor lists with hall and stand, address, business e-mail, phone and product groups.",
            "intro": "Messe München hosts some of the world's largest trade fairs. This actor exports their exhibitor directories into a spreadsheet-ready dataset: company, stand, address, business contacts and product groups — in English or German.",
            "features": ["bauma, IFAT, BAU, automatica, ceramitec and more", "Hall and stand per exhibitor", "Address, business e-mail, phone, website", "Product groups and products", "One row per exhibitor or per product group"],
            "uses": ["Plan meetings before the fair", "Map the suppliers of a sector", "Watch which competitors exhibit", "Find suppliers by product group"],
            "faq": [("Which fairs work?", "Fairs that use Messe München's exhibitor directory, such as bauma, IFAT, BAU, automatica and ceramitec."),
                    ("Can I use the contacts for e-mail campaigns?", "In Germany, promotional e-mail to companies needs prior consent (§ 7 UWG).")],
        },
        "de": {
            "title": "Ausstellerliste Messe München exportieren – bauma, IFAT",
            "h1": "Ausstellerlisten der Messe München exportieren",
            "desc": "Ausstellerlisten von bauma, IFAT, BAU, automatica und ceramitec exportieren: Halle und Stand, Anschrift, geschäftliche E-Mail, Telefon, Produktgruppen.",
            "intro": "Die Messe München veranstaltet einige der größten Fachmessen der Welt. Dieser Actor exportiert ihre Ausstellerverzeichnisse als Tabelle: Firma, Stand, Anschrift, geschäftliche Kontaktdaten und Produktgruppen — auf Deutsch oder Englisch.",
            "features": ["bauma, IFAT, BAU, automatica, ceramitec und weitere", "Halle und Stand je Aussteller", "Anschrift, geschäftliche E-Mail, Telefon, Website", "Produktgruppen und Produkte", "Eine Zeile je Aussteller oder je Produktgruppe"],
            "uses": ["Messetermine vorbereiten", "Anbieter einer Branche erfassen", "Sehen, welche Wettbewerber ausstellen", "Lieferanten nach Produktgruppe finden"],
            "faq": [("Welche Messen funktionieren?", "Messen mit dem Ausstellerverzeichnis der Messe München, etwa bauma, IFAT, BAU, automatica und ceramitec."),
                    ("Darf ich die Kontakte für E-Mail-Werbung nutzen?", "Werbe-E-Mails an Firmen brauchen in Deutschland eine vorherige Einwilligung (§ 7 UWG).")],
        },
    },
    "anuga-ism-koelnmesse-exhibitor-scraper": {
        "icon": "koelnmesse-256.png", "group": "sales",
        "unit": {"en": "exhibitors", "de": "Aussteller"},
        "example": {"fair": "anuga", "result_limit": 500},
        "en": {
            "title": "Koelnmesse Exhibitor List Scraper – Anuga, ISM, imm",
            "h1": "Export exhibitor lists of Koelnmesse trade fairs",
            "desc": "Export Anuga, ISM, imm cologne, interzum, ORGATEC and more: company, hall and stand, address, business e-mail, phone, brands and product categories.",
            "intro": "Koelnmesse runs leading fairs for food, furniture and interiors. This actor exports their exhibitor directories with contacts, brands and the full product category tree — ready for a spreadsheet or CRM.",
            "features": ["Anuga, ISM, imm cologne, interzum, IDS, ORGATEC, spoga+gafa and more — pick the fair from a list", "Hall and stand per exhibitor", "Address, business e-mail, phone, website, brands", "Product groups, target markets, sales channels", "One row per exhibitor or per product category"],
            "uses": ["Prepare meetings at the fair", "Find suppliers and distributors", "Track competitors and brands", "Size a sector by country"],
            "faq": [("Which fairs work?", "Fairs on Koelnmesse's exhibitor platform, such as Anuga, ISM, imm cologne, interzum, ORGATEC and spoga+gafa."),
                    ("Can I use the contacts for e-mail campaigns?", "In Germany, promotional e-mail to companies needs prior consent (§ 7 UWG).")],
        },
        "de": {
            "title": "Ausstellerliste Koelnmesse exportieren – Anuga, ISM, imm",
            "h1": "Ausstellerlisten der Koelnmesse exportieren",
            "desc": "Anuga, ISM, imm cologne, interzum, ORGATEC und mehr: Firma, Halle und Stand, Anschrift, geschäftliche E-Mail, Telefon, Marken und Produktkategorien.",
            "intro": "Die Koelnmesse veranstaltet Leitmessen für Lebensmittel, Möbel und Einrichtung. Dieser Actor exportiert ihre Ausstellerverzeichnisse mit Kontaktdaten, Marken und dem vollständigen Produktkategorien-Baum — fertig für Tabelle oder CRM.",
            "features": ["Anuga, ISM, imm cologne, interzum, IDS, ORGATEC, spoga+gafa und weitere — Messe einfach auswählen", "Halle und Stand je Aussteller", "Anschrift, geschäftliche E-Mail, Telefon, Website, Marken", "Produktgruppen, Zielmärkte, Vertriebswege", "Eine Zeile je Aussteller oder je Produktkategorie"],
            "uses": ["Messetermine vorbereiten", "Lieferanten und Händler finden", "Wettbewerber und Marken beobachten", "Branchen nach Ländern vermessen"],
            "faq": [("Welche Messen funktionieren?", "Messen auf der Ausstellerplattform der Koelnmesse, etwa Anuga, ISM, imm cologne, interzum, ORGATEC und spoga+gafa."),
                    ("Darf ich die Kontakte für E-Mail-Werbung nutzen?", "Werbe-E-Mails an Firmen brauchen in Deutschland eine vorherige Einwilligung (§ 7 UWG).")],
        },
    },
    "kununu-employer-data-scraper": {
        "icon": "kununu-256.png", "group": "research",
        "unit": {"en": "records", "de": "Datensätze"},
        "example": {"companies": ["https://www.kununu.com/de/siemens", "https://www.kununu.com/de/sap"], "include_reviews": True, "max_reviews_per_company": 100},
        "en": {
            "title": "kununu Scraper – Employer Reviews, Salaries & Benefits",
            "h1": "Export kununu employer ratings, salaries and reviews",
            "desc": "Export kununu employer ratings with industry comparison, category scores, benefits, salary ranges per job title and full reviews for DACH companies.",
            "intro": "kununu is the leading employer review platform in Germany, Austria and Switzerland. This actor exports an employer's score with industry comparison, ratings per category, confirmed benefits, salary ranges per job title and — on request — individual reviews.",
            "features": ["kununu score with industry comparison", "Ratings per category and sub-factor", "Benefits with share of confirmations", "Salary ranges per job title", "Individual reviews with employer replies"],
            "uses": ["Benchmark employer branding against competitors", "Compare salaries per role", "Analyse review sentiment", "Enrich recruiting and CRM data"],
            "faq": [("Which countries are covered?", "Germany, Austria and Switzerland — kununu's three markets."),
                    ("Are reviewers' names included?", "No. kununu reviews are anonymous, and the actor returns no personal data.")],
        },
        "de": {
            "title": "kununu Scraper – Arbeitgeberbewertungen & Gehälter",
            "h1": "kununu-Bewertungen, Gehälter und Benefits exportieren",
            "desc": "kununu-Arbeitgeberbewertungen exportieren: Score mit Branchenvergleich, Bewertungen je Kategorie, Benefits, Gehaltsspannen je Jobtitel und einzelne Bewertungen.",
            "intro": "kununu ist das führende Bewertungsportal für Arbeitgeber in Deutschland, Österreich und der Schweiz. Dieser Actor exportiert den kununu-Score mit Branchenvergleich, Bewertungen je Kategorie, bestätigte Benefits, Gehaltsspannen je Jobtitel und auf Wunsch einzelne Bewertungen.",
            "features": ["kununu-Score mit Branchenvergleich", "Bewertungen je Kategorie und Unterfaktor", "Benefits mit Bestätigungsquote", "Gehaltsspannen je Jobtitel", "Einzelne Bewertungen mit Arbeitgeber-Antworten"],
            "uses": ["Employer Branding mit Wettbewerbern vergleichen", "Gehälter je Rolle vergleichen", "Stimmung in Bewertungen auswerten", "Recruiting- und CRM-Daten anreichern"],
            "faq": [("Welche Länder sind abgedeckt?", "Deutschland, Österreich und die Schweiz — die drei Märkte von kununu."),
                    ("Werden Namen von Bewertenden ausgegeben?", "Nein. kununu-Bewertungen sind anonym, der Actor liefert keine personenbezogenen Daten.")],
        },
    },
    "arbeitsagentur-jobs-scraper": {
        "icon": "arbeitsagentur-256.png", "group": "research",
        "unit": {"en": "jobs", "de": "Stellen"},
        "example": {"keyword": "Elektriker", "location": "München", "radiusKm": 25, "includeDetails": True},
        "en": {
            "title": "Arbeitsagentur Jobs Scraper – German Jobs via Official API",
            "h1": "Export job postings from Germany's federal job board",
            "desc": "Export jobs from the Bundesagentur für Arbeit Jobbörse via its official API: title, employer, salary, home office, working time, location and full description.",
            "intro": "The Jobbörse of the Bundesagentur für Arbeit is Germany's largest job board. This actor uses its official public API — no HTML scraping, no proxy — and returns structured job postings with salary information, home-office flags, locations and, optionally, the full description.",
            "features": ["Official public API, no blocking", "Search by keyword, place and radius", "Filters for job type, working time, employer, date", "Salary, home office, contract duration", "Optional full job description"],
            "uses": ["Analyse the German labour market", "Track hiring of specific employers", "Benchmark salaries", "Power job boards and AI agents"],
            "faq": [("Is the data official?", "Yes — it comes from the Bundesagentur für Arbeit's public job search API."),
                    ("Can I exclude temp agencies?", "Yes, with the option to exclude Zeitarbeit (temporary employment agencies).")],
        },
        "de": {
            "title": "Stellenangebote der Arbeitsagentur exportieren (API)",
            "h1": "Stellenangebote der Arbeitsagentur als Datensatz exportieren",
            "desc": "Stellen aus der Jobbörse der Bundesagentur für Arbeit über die offizielle API exportieren: Titel, Arbeitgeber, Gehalt, Homeoffice, Arbeitsort, Stellenbeschreibung.",
            "intro": "Die Jobbörse der Bundesagentur für Arbeit ist Deutschlands größte Stellenbörse. Dieser Actor nutzt ihre offizielle, öffentliche Schnittstelle — kein HTML-Scraping, kein Proxy — und liefert strukturierte Stellenangebote mit Gehaltsangaben, Homeoffice-Kennzeichen, Arbeitsorten und auf Wunsch der vollständigen Beschreibung.",
            "features": ["Offizielle öffentliche Schnittstelle, keine Sperren", "Suche nach Stichwort, Ort und Umkreis", "Filter für Angebotsart, Arbeitszeit, Arbeitgeber, Datum", "Gehalt, Homeoffice, Befristung", "Optional vollständige Stellenbeschreibung"],
            "uses": ["Den deutschen Arbeitsmarkt analysieren", "Einstellungen bestimmter Arbeitgeber verfolgen", "Gehälter vergleichen", "Jobportale und KI-Agenten versorgen"],
            "faq": [("Sind die Daten offiziell?", "Ja — sie stammen aus der öffentlichen Jobsuche-Schnittstelle der Bundesagentur für Arbeit."),
                    ("Kann ich Zeitarbeit ausschließen?", "Ja, dafür gibt es eine eigene Option.")],
        },
    },
    "appstore-google-play-intelligence": {
        "icon": "appstores-256.png", "group": "research",
        "unit": {"en": "apps", "de": "Apps"},
        "example": {"mode": "search", "keywords": ["budget planner"], "country": "de", "max_items": 50},
        "en": {
            "title": "App Store & Google Play Scraper – Ratings, Reviews, Ranks",
            "h1": "App Store and Google Play data in one dataset",
            "desc": "Search the App Store by keyword and load apps from Apple and Google Play into one table: ratings, rating counts, price, version, keyword rank and reviews.",
            "intro": "Most app scrapers cover one store. This actor returns Apple App Store and Google Play apps with the same field names, so an app can be compared across both stores row by row — plus keyword rankings and up to 500 recent App Store reviews per app.",
            "features": ["App Store keyword search with ranking position", "Apple and Google Play in one schema", "Rating, rating count, price, version, update date", "Up to 500 recent App Store reviews per app", "Twelve country store fronts"],
            "uses": ["App store optimisation (ASO)", "Track competitors' ratings and releases", "Size an app category before building", "Mine reviews for feature requests"],
            "faq": [("Can it search Google Play by keyword?", "No — Google Play has no stable public search endpoint, so Play apps are loaded by package name."),
                    ("Are Google Play reviews included?", "No. Google publishes no public review feed; App Store reviews are available.")],
        },
        "de": {
            "title": "App-Store- und Google-Play-Daten exportieren",
            "h1": "App Store und Google Play in einem Datensatz",
            "desc": "App Store nach Suchbegriffen durchsuchen und Apps aus Apple und Google Play in eine Tabelle laden: Bewertung, Anzahl Bewertungen, Preis, Version, Rang, Rezensionen.",
            "intro": "Die meisten App-Scraper decken nur einen Store ab. Dieser Actor liefert Apps aus dem Apple App Store und Google Play mit denselben Feldnamen — so lässt sich eine App zeilenweise über beide Stores vergleichen. Dazu Keyword-Rankings und bis zu 500 aktuelle App-Store-Rezensionen je App.",
            "features": ["App-Store-Suche nach Stichwort mit Rangposition", "Apple und Google Play in einem Schema", "Bewertung, Anzahl, Preis, Version, Aktualisierung", "Bis zu 500 aktuelle App-Store-Rezensionen je App", "Zwölf Länder-Stores, darunter Deutschland, Österreich, Schweiz"],
            "uses": ["App-Store-Optimierung (ASO)", "Bewertungen und Updates von Wettbewerbern verfolgen", "Eine App-Kategorie vor dem Bau vermessen", "Rezensionen nach Wünschen auswerten"],
            "faq": [("Kann man Google Play nach Stichwort durchsuchen?", "Nein — Google Play hat keine stabile öffentliche Suche; Play-Apps werden über den Paketnamen geladen."),
                    ("Gibt es Google-Play-Rezensionen?", "Nein. Google veröffentlicht keinen Rezensions-Feed; App-Store-Rezensionen sind enthalten.")],
        },
    },
    "eu-tenders-ted-scraper": {
        "icon": "ted-256.png", "group": "public",
        "unit": {"en": "tenders", "de": "Ausschreibungen"},
        "example": {"countries": ["DEU", "AUT"], "cpv_codes": ["72"], "only_open_tenders": True},
        "en": {
            "title": "TED Tenders API – EU Public Procurement Scraper",
            "h1": "Search and export EU public tenders from TED",
            "desc": "Export public tenders from all 27 EU member states via TED's official search API: buyer, value, deadline, CPV codes, winners and document links.",
            "intro": "TED (Tenders Electronic Daily) publishes public procurement across the EU. This actor uses TED's official search API and returns clean, one-language records — buyer, estimated value, deadline with days remaining, CPV labels, winners and links to the documents.",
            "features": ["All 27 EU member states", "Filters: country, CPV code, keyword, deadline, open only", "Buyer, estimated value, deadline, procedure type", "Contract award winners", "Records in your chosen language"],
            "uses": ["Daily tender monitoring by schedule", "Sell to public buyers", "Analyse competitors' contract wins", "Research public spending by sector"],
            "faq": [("Is this the official TED data?", "Yes — it uses TED's public search API, the official source for EU public procurement notices."),
                    ("Can I get only tenders I can still bid on?", "Yes, with the 'only open tenders' option.")],
        },
        "de": {
            "title": "EU-Ausschreibungen aus TED exportieren (offizielle API)",
            "h1": "Öffentliche Ausschreibungen der EU aus TED exportieren",
            "desc": "Öffentliche Ausschreibungen aller 27 EU-Staaten über die offizielle TED-API exportieren: Auftraggeber, Auftragswert, Frist, CPV-Codes, Zuschläge, Dokumente.",
            "intro": "TED (Tenders Electronic Daily) veröffentlicht die öffentlichen Ausschreibungen der EU. Dieser Actor nutzt die offizielle Such-Schnittstelle und liefert saubere, einsprachige Datensätze — Auftraggeber, geschätzter Wert, Frist mit verbleibenden Tagen, CPV-Bezeichnungen, Zuschläge und Links zu den Unterlagen.",
            "features": ["Alle 27 EU-Mitgliedstaaten", "Filter: Land, CPV-Code, Stichwort, Frist, nur offene", "Auftraggeber, geschätzter Wert, Frist, Verfahrensart", "Zuschlagsempfänger", "Datensätze in Ihrer Sprache, auch Deutsch"],
            "uses": ["Tägliches Ausschreibungsmonitoring per Zeitplan", "Vertrieb an öffentliche Auftraggeber", "Zuschläge von Wettbewerbern auswerten", "Öffentliche Ausgaben nach Branche analysieren"],
            "faq": [("Sind das die offiziellen TED-Daten?", "Ja — der Actor nutzt die öffentliche Such-Schnittstelle von TED, die amtliche Quelle für EU-Ausschreibungen."),
                    ("Nur Ausschreibungen, auf die man noch bieten kann?", "Ja, mit der Option „nur offene Ausschreibungen“.")],
        },
    },
    "german-energy-assets-mastr": {
        "icon": "mastr-256.png", "group": "public",
        "unit": {"en": "units", "de": "Anlagen"},
        "example": {"energy_source": "solar", "federal_state": "BY", "min_power_kw": 750, "commissioned_before": "2012-01-01"},
        "en": {
            "title": "Marktstammdatenregister (MaStR) Scraper – Solar & Wind",
            "h1": "Export Germany's solar, wind and storage plants from the MaStR",
            "desc": "Export solar parks, wind turbines and battery storage from Germany's Marktstammdatenregister: operator, capacity, commissioning date, location, grid operator.",
            "intro": "Every power generation unit in Germany must be registered in the Marktstammdatenregister (MaStR) of the Bundesnetzagentur. This actor exports it with plain filters — energy source, state, capacity, age — and returns only named operators by default, so the data contains companies, not private persons.",
            "features": ["Solar, wind, storage, biomass, hydro, gas", "Filters: state, capacity, commissioning date, status", "Operator, capacity, plant age, grid operator", "Address and coordinates where available", "Licence dl-de/by-2-0, commercial use allowed"],
            "uses": ["Repowering and O&M leads (plants older than 15 years)", "Battery storage and PPA project development", "Grid and energy consulting", "Energy transition research"],
            "faq": [("Is commercial use allowed?", "Yes. The register's licence (dl-de/by-2-0) allows commercial use with attribution, which every record carries."),
                    ("Are private operators included?", "Not by default — the register anonymises private persons, and the actor keeps only named operators.")],
        },
        "de": {
            "title": "Marktstammdatenregister exportieren – Solar, Wind, Speicher",
            "h1": "Solarparks, Windkraft und Speicher aus dem Marktstammdatenregister exportieren",
            "desc": "Solarparks, Windenergieanlagen und Batteriespeicher aus dem Marktstammdatenregister (MaStR) exportieren: Betreiber, Leistung, Inbetriebnahme, Standort, Netzbetreiber.",
            "intro": "Jede Stromerzeugungsanlage in Deutschland muss im Marktstammdatenregister (MaStR) der Bundesnetzagentur stehen. Dieser Actor exportiert es mit einfachen Filtern — Energieträger, Bundesland, Leistung, Alter — und liefert standardmäßig nur Anlagen mit benanntem Betreiber, also Firmen statt Privatpersonen.",
            "features": ["Solar, Wind, Speicher, Biomasse, Wasser, Gas", "Filter: Bundesland, Leistung, Inbetriebnahme, Status", "Betreiber, Leistung, Anlagenalter, Netzbetreiber", "Anschrift und Koordinaten, wo vorhanden", "Lizenz dl-de/by-2-0, kommerzielle Nutzung erlaubt"],
            "uses": ["Repowering- und Wartungs-Leads (Anlagen über 15 Jahre)", "Speicher- und PPA-Projektentwicklung", "Netz- und Energieberatung", "Forschung zur Energiewende"],
            "faq": [("Ist kommerzielle Nutzung erlaubt?", "Ja. Die Lizenz dl-de/by-2-0 erlaubt sie mit Namensnennung; jeder Datensatz trägt die Angabe mit."),
                    ("Sind Privatpersonen enthalten?", "Standardmäßig nicht — das Register anonymisiert Privatpersonen, der Actor behält nur benannte Betreiber.")],
        },
    },
    "eudamed-medical-device-scraper": {
        "icon": "eudamed-256.png", "group": "public",
        "unit": {"en": "records", "de": "Datensätze"},
        "example": {"mode": "devices", "risk_class": "refdata.risk-class.class-iii", "max_items": 200},
        "en": {
            "title": "EUDAMED Scraper – EU Medical Devices (MDR & IVDR)",
            "h1": "Export EU medical devices, manufacturers and certificates from EUDAMED",
            "desc": "Export devices, manufacturers and notified-body certificates from EUDAMED: risk class, market status, sterility, latex, CND codes and warnings in plain language.",
            "intro": "EUDAMED is the EU's mandatory medical device database under MDR and IVDR. This actor exports devices, economic operators and certificates and resolves its codes into plain language — risk class, market status, sterility, CMR substances, market availability per country and warnings.",
            "features": ["Devices, manufacturers, importers, certificates", "Risk class, market status, sterility, latex, CMR", "Market availability per EU country", "CND codes and 423 warning texts in plain language", "Filters by risk class, status, Primary DI, Basic UDI-DI"],
            "uses": ["Regulatory intelligence", "Competitor product mapping", "Market access research", "Supplier and manufacturer checks"],
            "faq": [("Is there an official EUDAMED export?", "No bulk export exists; this actor reads the same public data as the EUDAMED website and returns it as structured records."),
                    ("How fast is it?", "EUDAMED's own speed varies during the day; the actor paces itself and stops cleanly before your run timeout.")],
        },
        "de": {
            "title": "EUDAMED exportieren – EU-Medizinprodukte (MDR & IVDR)",
            "h1": "Medizinprodukte, Hersteller und Zertifikate aus EUDAMED exportieren",
            "desc": "Medizinprodukte, Hersteller und Zertifikate benannter Stellen aus EUDAMED exportieren: Risikoklasse, Marktstatus, Sterilität, CND-Codes und Warnhinweise im Klartext.",
            "intro": "EUDAMED ist die verpflichtende EU-Datenbank für Medizinprodukte nach MDR und IVDR. Dieser Actor exportiert Produkte, Wirtschaftsakteure und Zertifikate und übersetzt die Codes in Klartext — Risikoklasse, Marktstatus, Sterilität, CMR-Stoffe, Marktverfügbarkeit je Land und Warnhinweise.",
            "features": ["Produkte, Hersteller, Importeure, Zertifikate", "Risikoklasse, Marktstatus, Sterilität, Latex, CMR", "Marktverfügbarkeit je EU-Land", "CND-Codes und 423 Warnhinweise im Klartext", "Filter nach Risikoklasse, Status, Primary DI, Basic UDI-DI"],
            "uses": ["Regulatory Intelligence", "Produkte von Wettbewerbern erfassen", "Marktzugang recherchieren", "Hersteller und Lieferanten prüfen"],
            "faq": [("Gibt es einen offiziellen EUDAMED-Export?", "Einen Gesamtexport gibt es nicht; der Actor liest dieselben öffentlichen Daten wie die EUDAMED-Website und liefert sie strukturiert."),
                    ("Wie schnell ist er?", "EUDAMED selbst schwankt im Tagesverlauf; der Actor drosselt sich und endet sauber vor dem Zeitlimit des Laufs.")],
        },
    },
    "dach-eu-data-source-finder": {
        "icon": "finder-256.png", "group": "free",
        "unit": {"en": "queries", "de": "Anfragen"},
        "example": {"queries": ["bauma exhibitor list", "Impressum Daten", "PDF to Markdown"]},
        "en": {
            "title": "DACH & EU Data Source Finder – Free",
            "h1": "Find the right ready-made scraper for your data source — free",
            "desc": "Free lookup: name a website, trade fair, register or document type and learn which ready-made actor covers it, which fields you get and what a run costs.",
            "intro": "Not sure which actor fits? Describe the data you need — a website, a trade fair, a register, a document type — and this free actor tells you which ready-made actor covers it, what fields come back and what a run costs.",
            "features": ["Free, no setup", "Matches websites, fairs, registers and document types", "Fields, record volume and price per match", "Plain answer when nothing fits"],
            "uses": ["Choose the right actor before running", "Check whether a source is already covered"],
            "faq": [("Does it cost anything?", "No actor fee. A run takes a few seconds of platform time."),
                    ("What if nothing matches?", "It says so plainly instead of guessing.")],
        },
        "de": {
            "title": "Datenquellen-Finder für DACH & EU – kostenlos",
            "h1": "Den passenden Scraper für Ihre Datenquelle finden — kostenlos",
            "desc": "Kostenlos: Website, Messe, Register oder Dokumenttyp nennen und erfahren, welcher fertige Actor die Daten liefert, welche Felder kommen und was ein Lauf kostet.",
            "intro": "Unsicher, welcher Actor passt? Beschreiben Sie die gesuchten Daten — eine Website, eine Messe, ein Register, einen Dokumenttyp — und dieser kostenlose Actor nennt den passenden fertigen Actor, die gelieferten Felder und die Kosten eines Laufs.",
            "features": ["Kostenlos, ohne Einrichtung", "Findet Websites, Messen, Register und Dokumenttypen", "Felder, Datenmenge und Preis je Treffer", "Klare Antwort, wenn nichts passt"],
            "uses": ["Vor dem Lauf den richtigen Actor wählen", "Prüfen, ob eine Quelle schon abgedeckt ist"],
            "faq": [("Kostet das etwas?", "Keine Actor-Gebühr. Ein Lauf dauert wenige Sekunden Plattformzeit."),
                    ("Und wenn nichts passt?", "Dann sagt er das klar, statt zu raten.")],
        },
    },
}
